// Copyright 2026 The AccessKit Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0 (found in
// the LICENSE-APACHE file) or the MIT license (found in
// the LICENSE-MIT file), at your option.

use accesskit_consumer::{FilterResult, Node, NodeId, TreeChangeHandler};
use objc2_ui_kit::{
    UIAccessibilityLayoutChangedNotification, UIAccessibilityNotifications,
    UIAccessibilityPostNotification,
};
use std::collections::VecDeque;
use std::rc::Rc;

use crate::{context::Context, filters::filter, node::PlatformNode};

pub(crate) enum QueuedEvent {
    Generic {
        node_id: Option<NodeId>,
        notification: UIAccessibilityNotifications,
    },
    NodeDestroyed(NodeId),
}

impl QueuedEvent {
    fn raise(self, context: &Rc<Context>) {
        match self {
            Self::Generic {
                node_id,
                notification,
            } => {
                let argument = node_id
                    .and_then(|id| context.get_or_create_platform_node(id))
                    .map(PlatformNode::into_any_object);
                unsafe {
                    UIAccessibilityPostNotification(notification, argument.as_deref());
                }
            }
            Self::NodeDestroyed(node_id) => {
                context.remove_platform_node(node_id);
            }
        }
    }
}

/// Events generated by a tree update.
#[must_use = "events must be explicitly raised"]
pub struct QueuedEvents {
    context: Rc<Context>,
    events: Vec<QueuedEvent>,
}

impl QueuedEvents {
    pub(crate) fn new(context: Rc<Context>, events: Vec<QueuedEvent>) -> Self {
        Self { context, events }
    }

    /// Raise all queued events synchronously.
    ///
    /// It is unknown whether accessibility methods on the view may be
    /// called while events are being raised. This means that any locks
    /// or runtime borrows required to access the adapter must not
    /// be held while this method is called.
    pub fn raise(self) {
        for event in self.events {
            event.raise(&self.context);
        }
    }
}

pub(crate) fn layout_event(node_id: Option<NodeId>) -> QueuedEvent {
    QueuedEvent::Generic {
        node_id,
        notification: unsafe { UIAccessibilityLayoutChangedNotification },
    }
}

pub(crate) struct EventGenerator {
    context: Rc<Context>,
    layout_event_focus: Option<Option<NodeId>>,
    events: Vec<QueuedEvent>,
}

impl EventGenerator {
    pub(crate) fn new(context: Rc<Context>) -> Self {
        Self {
            context,
            layout_event_focus: None,
            events: Vec::new(),
        }
    }

    fn insert_focus_moved_event_if_needed(&mut self, focus: NodeId) {
        if *self.context.platform_focus.borrow() != Some(focus) {
            self.layout_event_focus = Some(Some(focus));
        }
    }

    fn insert_layout_changed_event_if_needed(&mut self) {
        if self.layout_event_focus.is_none() {
            self.layout_event_focus = Some(None);
        }
    }

    fn remove_subtree(&mut self, node: &Node) {
        let mut to_remove = VecDeque::new();
        to_remove.push_back(*node);

        while let Some(node) = to_remove.pop_front() {
            for child in node.filtered_children(&filter) {
                to_remove.push_back(child);
            }

            self.events.push(QueuedEvent::NodeDestroyed(node.id()));
        }
    }

    pub(crate) fn into_result(self) -> QueuedEvents {
        let mut events = self
            .layout_event_focus
            .map(|focus| vec![layout_event(focus)])
            .unwrap_or_default();
        events.extend(self.events);
        QueuedEvents::new(self.context, events)
    }
}

impl TreeChangeHandler for EventGenerator {
    fn node_added(&mut self, node: &Node) {
        if filter(node) != FilterResult::Include {
            return;
        }
        self.insert_layout_changed_event_if_needed();
    }

    fn node_updated(&mut self, old_node: &Node, new_node: &Node) {
        let old_included = filter(old_node) == FilterResult::Include;
        let new_filter_result = filter(new_node);
        let new_included = new_filter_result == FilterResult::Include;

        if old_included && !new_included {
            self.insert_layout_changed_event_if_needed();
            if new_filter_result == FilterResult::ExcludeSubtree {
                self.remove_subtree(old_node);
            } else {
                self.events.push(QueuedEvent::NodeDestroyed(new_node.id()));
            }
            return;
        }

        if new_included {
            self.insert_layout_changed_event_if_needed();
        }
    }

    fn focus_moved(&mut self, _old_node: Option<&Node>, new_node: Option<&Node>) {
        if let Some(new_node) = new_node {
            if filter(new_node) != FilterResult::Include {
                return;
            }
            self.insert_focus_moved_event_if_needed(new_node.id());
        }
    }

    fn node_removed(&mut self, node: &Node) {
        if filter(node) != FilterResult::Include {
            return;
        }
        self.insert_layout_changed_event_if_needed();
        self.events.push(QueuedEvent::NodeDestroyed(node.id()));
    }
}
