// Copyright 2026 The AccessKit Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0 (found in
// the LICENSE-APACHE file) or the MIT license (found in
// the LICENSE-MIT file), at your option.

use accesskit::Live;
use accesskit_consumer::{FilterResult, Node, NodeId, TreeChangeHandler};
use objc2::runtime::{AnyObject, ProtocolObject};
use objc2_foundation::{
    NSAttributedString, NSAttributedStringKey, NSMutableDictionary, NSNumber, NSString,
};
use objc2_ui_kit::{
    UIAccessibilityAnnouncementNotification, UIAccessibilityLayoutChangedNotification,
    UIAccessibilityNotifications, UIAccessibilityPostNotification, UIAccessibilityPriority,
    UIAccessibilityPriorityHigh, UIAccessibilityPriorityLow,
    UIAccessibilityScreenChangedNotification, UIAccessibilitySpeechAttributeAnnouncementPriority,
    UIAccessibilitySpeechAttributeQueueAnnouncement,
};
use std::collections::VecDeque;
use std::rc::Rc;

use crate::{context::Context, filters::filter, node::PlatformNode};

pub(crate) enum QueuedEvent {
    Generic {
        node_id: Option<NodeId>,
        notification: UIAccessibilityNotifications,
    },
    NodeDestroyed(NodeId),
    Announcement {
        text: String,
        priority: &'static UIAccessibilityPriority,
    },
}

impl QueuedEvent {
    fn live_region_announcement(text: String, priority: Live) -> Self {
        Self::Announcement {
            text,
            priority: if priority == Live::Assertive {
                unsafe { UIAccessibilityPriorityHigh }
            } else {
                unsafe { UIAccessibilityPriorityLow }
            },
        }
    }

    fn raise(self, context: &Rc<Context>) {
        match self {
            Self::Generic {
                node_id,
                notification,
            } => {
                let argument = node_id
                    .and_then(|id| context.get_or_create_platform_node(id))
                    .map(PlatformNode::into_any_object);
                unsafe {
                    UIAccessibilityPostNotification(notification, argument.as_deref());
                }
            }
            Self::NodeDestroyed(node_id) => {
                context.remove_platform_node(node_id);
            }
            Self::Announcement { text, priority } => {
                Self::raise_announcement(&text, priority);
            }
        }
    }

    fn raise_announcement(text: &str, priority: &'static UIAccessibilityPriority) {
        let text = NSString::from_str(text);
        let mut attrs: objc2::rc::Retained<NSMutableDictionary<NSAttributedStringKey, AnyObject>> =
            NSMutableDictionary::new();
        unsafe {
            attrs.setObject_forKey(
                priority,
                ProtocolObject::from_ref(UIAccessibilitySpeechAttributeAnnouncementPriority),
            );
            attrs.setObject_forKey(
                &*NSNumber::new_bool(true),
                ProtocolObject::from_ref(UIAccessibilitySpeechAttributeQueueAnnouncement),
            );
        }
        let announcement = unsafe { NSAttributedString::new_with_attributes(&text, &attrs) };
        unsafe {
            UIAccessibilityPostNotification(
                UIAccessibilityAnnouncementNotification,
                Some(&announcement),
            );
        }
    }
}

/// Events generated by a tree update.
#[must_use = "events must be explicitly raised"]
pub struct QueuedEvents {
    context: Rc<Context>,
    events: Vec<QueuedEvent>,
}

impl QueuedEvents {
    pub(crate) fn new(context: Rc<Context>, events: Vec<QueuedEvent>) -> Self {
        Self { context, events }
    }

    /// Raise all queued events.
    ///
    /// It is unknown whether accessibility methods on the view may be
    /// called while events are being raised. This means that any locks
    /// or runtime borrows required to access the adapter must not
    /// be held while this method is called.
    pub fn raise(self) {
        for event in self.events {
            event.raise(&self.context);
        }
    }
}

pub(crate) fn layout_event(node_id: Option<NodeId>) -> QueuedEvent {
    QueuedEvent::Generic {
        node_id,
        notification: unsafe { UIAccessibilityLayoutChangedNotification },
    }
}

pub(crate) fn screen_changed_event(node_id: Option<NodeId>) -> QueuedEvent {
    QueuedEvent::Generic {
        node_id,
        notification: unsafe { UIAccessibilityScreenChangedNotification },
    }
}

pub(crate) struct EventGenerator {
    context: Rc<Context>,
    platform_focus: Option<NodeId>,
    layout_event_focus: Option<Option<NodeId>>,
    events: Vec<QueuedEvent>,
}

impl EventGenerator {
    pub(crate) fn new(context: Rc<Context>) -> Self {
        let platform_focus = *context.platform_focus.borrow();
        Self {
            context,
            platform_focus,
            layout_event_focus: None,
            events: Vec::new(),
        }
    }

    fn insert_focus_moved_event_if_needed(&mut self, focus: NodeId) {
        if self.platform_focus != Some(focus) {
            self.layout_event_focus = Some(Some(focus));
        }
    }

    fn insert_layout_changed_event_if_needed(&mut self) {
        if self.layout_event_focus.is_none() {
            self.layout_event_focus = Some(None);
        }
    }

    fn remove_node(&mut self, id: NodeId) {
        self.insert_layout_changed_event_if_needed();
        if self.platform_focus == Some(id) {
            *self.context.platform_focus.borrow_mut() = None;
            self.platform_focus = None;
        }
        self.events.push(QueuedEvent::NodeDestroyed(id));
    }

    fn remove_subtree(&mut self, node: &Node) {
        let mut to_remove = VecDeque::new();
        to_remove.push_back(*node);

        while let Some(node) = to_remove.pop_front() {
            for child in node.filtered_children(&filter) {
                to_remove.push_back(child);
            }

            self.remove_node(node.id());
        }
    }

    pub(crate) fn into_result(self) -> QueuedEvents {
        let mut events = self.events;
        if let Some(focus) = self.layout_event_focus {
            events.push(layout_event(focus));
        }
        QueuedEvents::new(self.context, events)
    }
}

impl TreeChangeHandler for EventGenerator {
    fn node_added(&mut self, node: &Node) {
        if filter(node) != FilterResult::Include {
            return;
        }
        self.insert_layout_changed_event_if_needed();
        if let Some(value) = node.value() {
            if node.live() != Live::Off {
                self.events
                    .push(QueuedEvent::live_region_announcement(value, node.live()));
            }
        }
    }

    fn node_updated(&mut self, old_node: &Node, new_node: &Node) {
        let old_filter_result = filter(old_node);
        let old_included = old_filter_result == FilterResult::Include;
        let new_filter_result = filter(new_node);
        let new_included = new_filter_result == FilterResult::Include;

        if old_included && !new_included {
            if new_filter_result == FilterResult::ExcludeSubtree {
                self.remove_subtree(old_node);
            } else {
                self.remove_node(new_node.id());
            }
            return;
        }

        if new_included {
            self.insert_layout_changed_event_if_needed();
        }

        let was_filtered_out = old_filter_result != FilterResult::Include;
        if let Some(value) = new_node.value() {
            if new_node.live() != Live::Off
                && (Some(&value) != old_node.value().as_ref()
                    || new_node.live() != old_node.live()
                    || was_filtered_out)
            {
                self.events.push(QueuedEvent::live_region_announcement(
                    value,
                    new_node.live(),
                ));
            }
        }
    }

    fn focus_moved(&mut self, _old_node: Option<&Node>, new_node: Option<&Node>) {
        if let Some(new_node) = new_node {
            if filter(new_node) != FilterResult::Include {
                return;
            }
            self.insert_focus_moved_event_if_needed(new_node.id());
        }
    }

    fn node_removed(&mut self, node: &Node) {
        if filter(node) != FilterResult::Include {
            return;
        }
        self.remove_node(node.id());
    }
}
