[package]
name = "accesskit_mac"
version = "0.1.0"
edition = "2018"

[dependencies]
accesskit = { path = "../../common" }
accesskit_consumer = { path = "../../consumer" }
cocoa = "0.24.0"
lazy_static = "1.4.0"
objc = "0.2.7"

[dev-dependencies]
accesskit = { path = "../../common", features = ["serde"] }
serde_json = "1.0"
