[package]
name = "accesskit_mac"
version = "0.1.0"
edition = "2018"

[dependencies]
accesskit_consumer = { path = "../../consumer" }
accesskit_schema = { path = "../../schema" }
cocoa = "0.24.0"
lazy_static = "1.4.0"
objc = "0.2.7"

[dev-dependencies]
serde = "1.0"
serde_json = "1.0"
