[package]
name = "accesskit_mac"
version = "0.4.0"
authors = ["Matt Campbell <mattcampbell@pobox.com>", "Rain <rain@synth.kitchen>"]
license = "MIT/Apache-2.0"
description = "AccessKit UI accessibility infrastructure: macOS adapter"
categories = ["gui"]
keywords = ["gui", "ui", "accessibility"]
repository = "https://github.com/AccessKit/accesskit"
readme = "README.md"
edition = "2021"

[dependencies]
accesskit = { version = "0.4.0", path = "../../common" }
accesskit_consumer = { version = "0.4.0", path = "../../consumer" }
cocoa = "0.25.0"
lazy_static = "1.4.0"
objc = "0.2.7"

[dev-dependencies]
accesskit = { path = "../../common", features = ["serde"] }
serde_json = "1.0"
