set(ACCESSKIT_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/include")
if (APPLE)
    set(_ACCESSKIT_OS "macos")
elseif (UNIX)
    set(_ACCESSKIT_OS "linux")
elseif (WIN32)
    set(_ACCESSKIT_OS "windows")
    if (MINGW)
        set(_ACCESSKIT_TOOLCHAIN "mingw/")
    else()
        set(_ACCESSKIT_TOOLCHAIN "msvc/")
    endif()
    if (CMAKE_VS_PLATFORM_NAME)
        string(TOLOWER "${CMAKE_VS_PLATFORM_NAME}" LOWER_VS_PLATFORM_NAME)
        if ("${LOWER_VS_PLATFORM_NAME}" STREQUAL "arm64")
            set(_ACCESSKIT_ARCH "arm64")
        endif()
    endif()
endif()
if (NOT _ACCESSKIT_TOOLCHAIN)
    set(_ACCESSKIT_TOOLCHAIN "")
endif()
if (NOT _ACCESSKIT_ARCH)
    if (CMAKE_SYSTEM_PROCESSOR MATCHES "^(AMD64|amd64|x86_64)$")
        set(_ACCESSKIT_ARCH "x86_64")
    elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "^(ARM64|arm64|aarch64)$")
        set(_ACCESSKIT_ARCH "arm64")
    elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "^(X86|x86|i686)$")
        set(_ACCESSKIT_ARCH "x86")
    endif()
endif()
set(ACCESSKIT_LIBRARIES_DIR "${CMAKE_CURRENT_LIST_DIR}/lib/${_ACCESSKIT_OS}/${_ACCESSKIT_ARCH}/${_ACCESSKIT_TOOLCHAIN}")
find_library(ACCESSKIT_LIBRARIES accesskit ${ACCESSKIT_LIBRARIES_DIR}/static)
