[package]
name = "accesskit_mac_jni"
version = "0.1.0"
edition = "2018"

[dependencies]
accesskit_mac = { path = ".." }
accesskit_schema = { path = "../../../schema" }
cocoa = "0.24.0"
jni = "0.19.0"
serde = "1.0"
serde_json = "1.0"

[lib]
crate_type = ["cdylib"]
