[package]
name = "accesskit_linux"
version = "0.1.0"
edition = "2018"

[dependencies]
accesskit = { version = "0.7.0", path = "../../common" }
accesskit_consumer = { version = "0.7.1", path = "../../consumer" }
enumflags2 = "0.7.1"
parking_lot = "0.11.1"
serde = "1.0"
strum = { version = "0.23.0", features = ["derive"] }
zbus = "3.0.0"
zvariant = "3.6.0"

[dev-dependencies]
byteorder = "1.4.3"
winit = "0.27.2"
