[package]
name = "accesskit_linux"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
accesskit = { version = "0.1.1", path = "../../common" }
accesskit_consumer = { version = "0.1.1", path = "../../consumer" }
async-io = "1.4.1"
enumflags2 = "0.7.1"
lazy_static = "1.4.0"
parking_lot = "0.11.1"
serde = "1.0"
strum = { version = "0.23.0", features = ["derive"] }
x11rb = "0.8.1"
zbus = "2.0.0-beta.7"
zvariant = "2.9.0"

[dev-dependencies]
winit = "0.25.0"
