// Automatically generated by `cargo run -p accesskit_l10n_build`.
// Do not edit manually.

/// The locale tags that have translations, sorted for binary search. Each tag's
/// index is the key used by the lookup functions below.
static LOCALE_TAGS: &[&str] = &["en"];
/// Resolve a locale tag to its index in `LOCALE_TAGS`, or `None` if the tag has
/// no translations.
pub(crate) fn locale_index(locale: &str) -> Option<usize> {
    LOCALE_TAGS.binary_search(&locale).ok()
}
const EN: usize = 0;
#[allow(clippy::invisible_characters)]
pub(crate) fn lookup_impl(locale: usize, role: Role) -> Option<&'static str> {
    match (locale, role) {
        (EN, Role::Alert) => Some("alert"),
        (EN, Role::AlertDialog) => Some("alert dialog"),
        (EN, Role::Article) => Some("article"),
        (EN, Role::Banner) => Some("banner"),
        (EN, Role::Complementary) => Some("complementary"),
        (EN, Role::ContentInfo) => Some("content information"),
        (EN, Role::DocAbstract) => Some("abstract"),
        (EN, Role::DocAcknowledgements) => Some("acknowledgements"),
        (EN, Role::DocAfterword) => Some("afterword"),
        (EN, Role::DocAppendix) => Some("appendix"),
        (EN, Role::DocBackLink) => Some("back link"),
        (EN, Role::DocBiblioEntry) => Some("bibliography entry"),
        (EN, Role::DocBiblioRef) => Some("bibliography reference"),
        (EN, Role::DocBibliography) => Some("bibliography"),
        (EN, Role::DocChapter) => Some("chapter"),
        (EN, Role::DocColophon) => Some("colophon"),
        (EN, Role::DocConclusion) => Some("conclusion"),
        (EN, Role::DocCover) => Some("cover"),
        (EN, Role::DocCredit) => Some("credit"),
        (EN, Role::DocCredits) => Some("credits"),
        (EN, Role::DocDedication) => Some("dedication"),
        (EN, Role::DocEndnote) => Some("endnote"),
        (EN, Role::DocEndnotes) => Some("endnotes"),
        (EN, Role::DocEpigraph) => Some("epigraph"),
        (EN, Role::DocEpilogue) => Some("epilogue"),
        (EN, Role::DocErrata) => Some("errata"),
        (EN, Role::DocExample) => Some("example"),
        (EN, Role::DocFootnote) => Some("footnote"),
        (EN, Role::DocForeword) => Some("foreword"),
        (EN, Role::DocGlossRef) => Some("glossary reference"),
        (EN, Role::DocGlossary) => Some("glossary"),
        (EN, Role::DocIndex) => Some("index"),
        (EN, Role::DocIntroduction) => Some("introduction"),
        (EN, Role::DocNoteRef) => Some("note reference"),
        (EN, Role::DocNotice) => Some("notice"),
        (EN, Role::DocPageBreak) => Some("page break"),
        (EN, Role::DocPageFooter) => Some("page footer"),
        (EN, Role::DocPageHeader) => Some("page header"),
        (EN, Role::DocPageList) => Some("page list"),
        (EN, Role::DocPart) => Some("part"),
        (EN, Role::DocPreface) => Some("preface"),
        (EN, Role::DocPrologue) => Some("prologue"),
        (EN, Role::DocPullquote) => Some("pullquote"),
        (EN, Role::DocQna) => Some("question and answer"),
        (EN, Role::DocSubtitle) => Some("subtitle"),
        (EN, Role::DocTip) => Some("tip"),
        (EN, Role::DocToc) => Some("table of contents"),
        (EN, Role::Feed) => Some("feed"),
        (EN, Role::Figure) => Some("figure"),
        (EN, Role::Heading) => Some("heading"),
        (EN, Role::Log) => Some("log"),
        (EN, Role::Main) => Some("main"),
        (EN, Role::Navigation) => Some("navigation"),
        (EN, Role::Region) => Some("region"),
        (EN, Role::Search) => Some("search"),
        (EN, Role::Status) => Some("status"),
        (EN, Role::Tab) => Some("tab"),
        (EN, Role::Timer) => Some("timer"),
        _ => None,
    }
}
#[allow(clippy::invisible_characters)]
pub(crate) fn state_lookup_impl(locale: usize, key: StateKey) -> Option<&'static str> {
    match (locale, key) {
        (EN, StateKey::AriaCurrentDate) => Some("current date"),
        (EN, StateKey::AriaCurrentLocation) => Some("current location"),
        (EN, StateKey::AriaCurrentPage) => Some("current page"),
        (EN, StateKey::AriaCurrentStep) => Some("current step"),
        (EN, StateKey::AriaCurrentTime) => Some("current time"),
        (EN, StateKey::AriaCurrentTrue) => Some("current item"),
        (EN, StateKey::InvalidGrammar) => Some("Invalid grammar"),
        (EN, StateKey::InvalidSpelling) => Some("Invalid spelling"),
        (EN, StateKey::InvalidTrue) => Some("Invalid entry"),
        (EN, StateKey::LinkVisited) => Some("visited"),
        (EN, StateKey::MultiselectableNone) => Some("multiselectable, none selected."),
        (EN, StateKey::ToggleButtonOff) => Some("Off"),
        (EN, StateKey::ToggleButtonOn) => Some("On"),
        _ => None,
    }
}
/// An accessibility string with interpolated arguments, constructed by the
/// caller so the argument count is checked at compile time.
pub enum InterpolatedString<'a> {
    HeadingWithLevel(&'a str),
    Multiselectable(&'a str, &'a str),
    RadioChecked(&'a str, &'a str),
    RadioUnchecked(&'a str, &'a str),
}
/// Render `string` for the locale at `locale` (a `LOCALE_TAGS` index) into `out`.
#[allow(clippy::invisible_characters)]
pub(crate) fn write_interpolated_string_impl(
    locale: usize,
    string: InterpolatedString<'_>,
    out: &mut dyn core::fmt::Write,
) -> core::fmt::Result {
    match string {
        InterpolatedString::HeadingWithLevel(a0) => {
            match locale {
                _ => write!(out, "heading level {a0}"),
            }
        }
        InterpolatedString::Multiselectable(a0, a1) => {
            match locale {
                _ => write!(out, "multiselectable, {a0} of {a1} selected."),
            }
        }
        InterpolatedString::RadioChecked(a0, a1) => {
            match locale {
                _ => write!(out, "Checked. In group, option {a0} of {a1}"),
            }
        }
        InterpolatedString::RadioUnchecked(a0, a1) => {
            match locale {
                _ => write!(out, "Not checked. In group, option {a0} of {a1}"),
            }
        }
    }
}
